language: cpp

sudo: false

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - lua5.1
      - liblua5.1-0-dev
      - libboost1.55-all-dev
      
cache:
  - apt

script:
  - make -C Build config=release

