language: cpp

sudo: false

addons:
  apt:


addons:
  apt:
    sources:
      - boost-latest
    packages:
      - lua5.1
      - liblua5.1-0-dev
      - libboost1.55-all-dev

script:
  - make -C Build/linux/gmake config=release64

cache:
  - apt
